name: 'SQLake Execute Action'
description: 'Execute a SQL command using Upsolver SQLake'
inputs:
  path_to_sql:
    description: 'the relative path, in the local repo, to the files containing SQL code'
  file_list:
    description: 'a comma separated list of SQL files to execute'
  api_key:
    description: 'upsolver API key'
    required: true
    default: 'somekey'
outputs:
  query_results:
    description: 'Returns a JSON object with the query, output and error messages'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.path_to_sql }}
    - ${{ inputs.file_list }}
