name: 'SQL Execute Action'
description: 'Execute a SQL command using Upsolver SQLake'
inputs:
  worksheet_path:
    description: 'the local repo path to the worksheet'
    required: true
    default: '/src'
  api_key:
    description: 'upsolver API key'
    required: true
    default: 'somekey'
  profile_name:
    description: 'provide the profile name to use when executing a query'
    required: false
    default: 'profile'
outputs:
  query_results:
    description: 'Returns a JSON object with the query, output and error messages'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.profile_name }}
