on: [push]

jobs:
  list_catalogs:
    runs-on: ubuntu-latest
    name: listing catalogs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: list step
        uses: ./
        id: list_step
        with:
          profile: profile
          api_key: ${{ secrets.API_KEY }}
      - name: Print results
        run: echo ${{ steps.list_step.outputs.query_results }}
