on: [push]

jobs:
  run_worksheet:
    runs-on: ubuntu-latest
    name: Run Worksheet
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Worksheet
        uses: rhasson/sqlake_action@main
        id: run_step
        with:
          path_to_sql: src/worksheets
          api_key: ${{ secrets.API_KEY }}
          api_endpoint: 'https://api.upsolver.com'
      - name: Print Results
        run: |
          cat ${GITHUB_WORKSPACE}/execution_output.md >> $GITHUB_STEP_SUMMARY