on: [push]

jobs:
  run_worksheet:
    runs-on: ubuntu-latest
    name: Run Worksheet
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Worksheet
        uses: rhasson/sqlake_action@master
        id: run_step
        with:
          worksheet_path: /src/worksheets
          profile_name: profile
          api_key: ${{ secrets.API_KEY }}
      - name: Print Results
        run: echo ${{ steps.run_step.outputs.query_results }}
